version: '3.8'
services:
    mongodb:
        image: 'mongo'
    backend:
        build: ./server
        ports:
            - '3001:3001'
        depends_on:
            - mongodb
        environment:
            - DB_URI='mongodb+srv://root:root1234@cluster0.plzqshw.mongodb.net/?retryWrites=true&w=majority'
    frontend:
        build: ./client
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        depends_on:
            - backend