version: '3'
services:
  web:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
